const words_to_find = [
    "ALFA ROMEO",
    "AUDI",
    "BMW",
    "CITROEN",
    "DACIA",
    "FIAT",
    "FORD",
    "MERCEDES",
    "NISSAN",
    "OPEL",
    "PEUGEOT",
    "RENAULT",
    "SEAT",
    "TOYOTA",
    "VOLKSWAGEN",
    "ABARTH",
    "ALPINE",
    "ARO",
    "ASIA",
    "ASTON MARTIN",
    "AUVERLAND",
    "BENTLEY",
    "BERTONE",
    "BUGATTI",
    "BUICK",
    "CADILLAC",
    "CATERHAM",
    "CHEVROLET",
    "CHEYENNE",
    "CORVETTE",
    "CUPRA",
    "DAEWOO",
    "DAIHATSU",
    "DAIMLER",
    "DE TOMASO",
    "DODGE",
    "DONKERVOORT",
    "DS",
    "FERRARI",
    "FSO",
    "GENERAL MOTORS",
    "GRANDIN",
    "HOMMEL",
    "HONDA",
    "HUMMER",
    "HYUNDAI",
    "INFINITI",
    "ISUZU",
    "IVECO",
    "JAGUAR",
    "JEEP",
    "KIA",
    "LADA",
    "LAMBORGHINI",
    "LANCIA",
    "LAND ROVER",
    "LANDWIND",
    "LDV",
    "LEXUS",
    "LOTUS",
    "MAHINDRA",
    "MAN",
    "MASERATI",
    "MAYBACH",
    "MAZDA",
    "MEGA",
    "MG",
    "MIA ELECTRIC",
    "MINI",
    "MITSUBISHI",
    "MORGAN",
    "PIAGGIO",
    "PONTIAC",
    "PORSCHE",
    "PROTON",
    "ROLLS ROYCE",
    "ROVER",
    "SAAB",
    "SAIC",
    "SANTANA",
    "SKODA",
    "MCC",
    "SSANGYONG",
    "SUBARU",
    "SUZUKI",
    "TATA",
    "TESLA",
    "TVR",
    "VENTURI",
    "VOLVO"
];

new HangedMan({
    parent_element: document.body.querySelector('main'),
    list_of_words: words_to_find,
});